name: Deploy Preview

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      BUCKET_NAME: jtl-preview-bucket
      REGION: us-east-1
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install
      - run: npm run build

      - name: Deploy to S3
        run: aws s3 sync ./dist s3://$BUCKET_NAME/pr-${{ github.event.number }}/ --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Comment Preview Link
        uses: actions/github-script@v7
        with:
            github-token: ${{secrets.GITHUB_TOKEN}}
            script: |
                github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: "🌐 Preview: http://$BUCKET_NAME.s3-website-$REGION.amazonaws.com/pr-${{ github.event.number }}/"
                })